@@ CreateTables
@@ InsertData
@@ addToHallofFameTrigger
@@ removeIdeaTrigger
@@ setSharesTrigger
@@ removeFromWatchListProcedure
@@ addToWatchListProcedure
@@ setSharesProcedure
@@ associateIdeaToTopicFunction
@@ createIdeaFunction