CREATE SEQUENCE user_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE topic_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE idea_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE transaction_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE fila_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE fame_seq INCREMENT BY 1 START WITH 1;